server:
  port: 8081

spring: 
  datasource:
    url: jdbc:mysql://39.106.130.199:3306/shiro?useSSL=true
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  freemarker: 
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    suffix: .html
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 0
    #password: 123456